### Traer todos los articulos 
GET  http://localhost:3000/articulos


### traer todos los articulos o de una categoria

GET  http://localhost:3000/articulos?categoria=accesorios



### Traer un producto por id

GET http://localhost:3000/articulos/667a2532530f9384dce22103


### Agregar un articulo
POST http://localhost:3000/articulos
Content-Type: application/json

{
    "codigo": 55,
    "nombre": "Parlante",
    "precio": 100,
    "categoria": "Accesorios"
    
}

### Actualizar un articulo 



PUT http://localhost:3000/articulos/6681712dd9f6a29d15989d57
Content-Type: application/json

{
    "codigo": 777,
    "nombre": "Parlante",
    "precio": 333,
    "categoria": "Accesorios"
}


### Eliminar un articulo

DELETE http://localhost:3000/articulos/66817819e1dd0ace70bca8ff